# Generated by Django 4.0.3 on 2022-04-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_delete_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='description_full',
        ),
        migrations.AddField(
            model_name='product',
            name='description_short',
            field=models.TextField(blank=True),
        ),
    ]
