# Generated by Django 4.0.3 on 2022-04-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='category',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='Картинка'),
        ),
    ]
