# Generated by Django 4.0.4 on 2022-04-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand_car',
            field=models.CharField(db_index=True, default='', max_length=30, verbose_name='Марка машины'),
        ),
        migrations.AddField(
            model_name='product',
            name='full_url',
            field=models.CharField(default='', max_length=300, verbose_name='Полный URL'),
        ),
        migrations.AddField(
            model_name='product',
            name='item_number',
            field=models.CharField(db_index=True, default='', max_length=100, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='product',
            name='model_car',
            field=models.CharField(db_index=True, default='', max_length=30, verbose_name='Модель машины'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_install',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена установки'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(default='', max_length=50, verbose_name='Тип товара (товар/услуга)'),
        ),
        migrations.AddField(
            model_name='product',
            name='seat_type',
            field=models.CharField(default='tab', max_length=250, verbose_name='Тип сиденья'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_desc',
            field=models.CharField(default='', max_length=250, verbose_name='SEO content'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_key',
            field=models.CharField(default='', max_length=100, verbose_name='SEO keys'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title',
            field=models.CharField(default='', max_length=100, verbose_name='SEO title'),
        ),
        migrations.AddField(
            model_name='product',
            name='year',
            field=models.CharField(db_index=True, default='', max_length=50, verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=250, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=250, verbose_name='Слаг'),
        ),
    ]
