# Generated by Django 4.0.4 on 2022-04-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_brand_car_product_full_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand_car',
            field=models.CharField(db_index=True, default='000', max_length=30, verbose_name='Марка машины'),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_number',
            field=models.CharField(db_index=True, default='000', max_length=100, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_car',
            field=models.CharField(db_index=True, default='000', max_length=30, verbose_name='Модель машины'),
        ),
    ]
