# Generated by Django 4.0.4 on 2022-04-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_product_brand_car_alter_product_item_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='full_url',
            field=models.CharField(default='https://', max_length=300, verbose_name='Полный URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(default='000', max_length=50, verbose_name='Тип товара (товар/услуга)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seat_type',
            field=models.CharField(default='000', max_length=250, verbose_name='Тип сиденья'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_desc',
            field=models.CharField(default='000', max_length=250, verbose_name='SEO content'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_key',
            field=models.CharField(default='000', max_length=100, verbose_name='SEO keys'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_title',
            field=models.CharField(default='000', max_length=100, verbose_name='SEO title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='year',
            field=models.CharField(db_index=True, default='000', max_length=50, verbose_name='Год выпуска'),
        ),
    ]
