# Generated by Django 4.0.4 on 2022-04-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_product_full_url_alter_product_product_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='full_url',
            field=models.CharField(default='https', max_length=300, verbose_name='Полный URL'),
        ),
    ]
