# Generated by Django 4.0.4 on 2022-04-17 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_subcategory_parent_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('name',), 'verbose_name_plural': 'Под категории'},
        ),
    ]
