# Generated by Django 4.0.4 on 2022-04-18 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_subcategory_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
