# Generated by Django 4.0.4 on 2022-04-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_delete_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand_car',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Марка машины'),
        ),
        migrations.AlterField(
            model_name='product',
            name='full_url',
            field=models.TextField(blank=True, verbose_name='Полный URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_car',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Модель машины'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(db_index=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(max_length=100, verbose_name='Тип (товар/услуга)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_key',
            field=models.TextField(verbose_name='SEO keys'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_title',
            field=models.TextField(verbose_name='SEO title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=500, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='year',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Год выпуска'),
        ),
    ]
