# Generated by Django 4.0.4 on 2022-04-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_category_name_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seo_desc',
            field=models.TextField(blank=True, verbose_name='SEO content'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_key',
            field=models.TextField(blank=True, verbose_name='SEO keys'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_title',
            field=models.TextField(blank=True, verbose_name='SEO title'),
        ),
    ]
