# Generated by Django 4.0.4 on 2022-04-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_order_alter_product_available_alter_product_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default='country', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='phone', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='region',
            field=models.CharField(default='region', max_length=100),
        ),
    ]
