# Generated by Django 4.0.4 on 2022-04-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_alter_orderitem_options_alter_order_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_base',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
