# Generated by Django 4.0.4 on 2022-04-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_alter_product_image_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_full',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_short',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='full_url',
            field=models.TextField(blank=True, null=True, verbose_name='Полный URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_desc',
            field=models.TextField(blank=True, null=True, verbose_name='SEO content'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_key',
            field=models.TextField(blank=True, null=True, verbose_name='SEO keys'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_title',
            field=models.TextField(blank=True, null=True, verbose_name='SEO title'),
        ),
    ]
