# Generated by Django 4.0.4 on 2022-05-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_alter_product_options_remove_product_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_install',
        ),
        migrations.AddField(
            model_name='product',
            name='price_install_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Максимальная цена установки'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_install_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Минимальная цена установки'),
        ),
    ]
