# Generated by Django 4.0.4 on 2022-05-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_remove_product_price_install_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_install_max',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_install_min',
        ),
        migrations.AddField(
            model_name='product',
            name='price_install',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Цена установки'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, choices=[('услуга', 'Услуга'), ('рейка', 'Рейка'), ('кронштейн', 'Кронштейн')], max_length=100, null=True, verbose_name='Тип товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Цена товара'),
        ),
    ]
