# Generated by Django 4.0.4 on 2022-05-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_alter_post_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='service_type',
            field=models.CharField(blank=True, choices=[('установка', 'Установка'), ('разработка', 'Разработка')], max_length=20, null=True, verbose_name='Тип товара'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, help_text='Читаемое название представленное в списке категорий', max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(help_text='Только: цифры, латинские символы, знаки тире и нижнего подчеркивания', max_length=200, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, choices=[('услуга', 'Услуга'), ('рейка', 'Рейка'), ('кронштейн', 'Кронштейн')], max_length=20, null=True, verbose_name='Тип товара'),
        ),
    ]
