# Generated by Django 4.0.4 on 2022-05-03 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_alter_product_created_alter_product_service_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated',
        ),
    ]
