# Generated by Django 4.0.4 on 2022-05-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_post_image_preview_alter_post_author_alter_post_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_preview',
            field=models.TextField(blank=True, verbose_name='предварительный текст'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_preview',
            field=models.ImageField(help_text='предварительное изображение', null=True, upload_to='blog_posts/%Y/%m/%d'),
        ),
    ]
