# Generated by Django 4.0.4 on 2022-05-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0046_remove_order_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Установка'), ('proc', 'Разработка'), ('arc', 'В архиве')], default='new', max_length=20, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, max_length=500, verbose_name='примечание к заказу'),
        ),
    ]
