# Generated by Django 4.0.4 on 2022-05-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0049_alter_category_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='grand_total',
            field=models.CharField(default='1000', max_length=20, verbose_name='итого'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(max_length=100, verbose_name='доставка'),
        ),
    ]
