# Generated by Django 4.0.4 on 2022-05-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0050_order_grand_total_alter_order_delivery_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_point',
            field=models.CharField(blank=True, max_length=100, verbose_name='пункт выдачи'),
        ),
    ]
