# Generated by Django 4.0.4 on 2022-06-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0051_order_delivery_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='install',
            field=models.BooleanField(default=False, verbose_name='установка'),
        ),
    ]
