# Generated by Django 4.0.4 on 2022-06-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0052_orderitem_install'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price_install',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='цена установки'),
        ),
    ]
