# Generated by Django 4.0.4 on 2022-06-02 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0053_orderitem_price_install'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_point',
        ),
    ]
