# Generated by Django 4.0.4 on 2022-06-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0054_remove_order_delivery_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attribute',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Атрибут'),
        ),
        migrations.AlterField(
            model_name='order',
            name='grand_total',
            field=models.CharField(max_length=20, verbose_name='Сумма заказа'),
        ),
    ]
