# Generated by Django 4.0.4 on 2022-06-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0056_order_yookassa_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_full_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='yookassa_full_info',
            field=models.TextField(blank=True),
        ),
    ]
