# Generated by Django 4.0.4 on 2022-06-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0057_order_address_full_info_order_yookassa_full_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='yookassa_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Юкасса сумма'),
        ),
        migrations.AddField(
            model_name='order',
            name='yookassa_status',
            field=models.CharField(blank=True, max_length=30, verbose_name='Юкасса статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='yookassa_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='Юкасса ID транзакции'),
        ),
    ]
