# Generated by Django 4.0.4 on 2022-06-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0059_alter_order_grand_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='policy',
            field=models.CharField(default=2, max_length=30, verbose_name='С политикой сайта'),
            preserve_default=False,
        ),
    ]
