# Generated by Django 4.0.4 on 2022-06-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0061_alter_order_created_alter_order_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='full_url',
        ),
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.ImageField(blank=True, upload_to='video/%Y/%m/%d', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('proc', 'На обработке'), ('arc', 'В архиве')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(blank=True, default=True, verbose_name='наличие'),
        ),
    ]
