# Generated by Django 4.0.4 on 2022-06-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0064_product_video_shot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='attribute',
            field=models.CharField(blank=True, default='', help_text='Поле используется для индефикации товара, в частности для "петли якорного крепления"', max_length=30, verbose_name='Атрибут'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(blank=True, default=True, help_text='Наличие товара, есть или нет', verbose_name='наличие'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand_car',
            field=models.CharField(blank=True, db_index=True, help_text='Текст', max_length=100, verbose_name='Марка машины'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_base',
            field=models.ImageField(blank=True, help_text='Основное изображение товара', upload_to='products/%Y/%m/%d', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_number',
            field=models.CharField(blank=True, db_index=True, help_text='Текст', max_length=100, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_car',
            field=models.CharField(blank=True, db_index=True, help_text='Текст', max_length=100, verbose_name='Модель машины'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, help_text='Категория товара', max_length=300, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Целые и плавающие числа', max_digits=10, verbose_name='Цена товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_install',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Целые и плавающие числа, у типа товара как услуга и для "петли якорного крепления" должно быть установлено 0', max_digits=10, verbose_name='Цена установки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, choices=[('услуга', 'Услуга'), ('рейка', 'Рейка'), ('кронштейн', 'Кронштейн')], help_text='Выбрать из списка тип товара, если выбрана услуга необходимо выбрать тип услуги ниже', max_length=20, verbose_name='Тип товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seat_type',
            field=models.CharField(blank=True, help_text='Текст', max_length=250, verbose_name='Тип сиденья'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_desc',
            field=models.TextField(blank=True, help_text='Нет необходимости заполнять это поле, если сюда вставлять текст со страницы, это будет         не правильно и в таком случае лучше оставить поле пустым', verbose_name='SEO content'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_key',
            field=models.TextField(blank=True, help_text='Например: кронштейн, рейка, рейки, установка, разработка и.т.д. Нет необходимомти         вставлять текст со строницы, это будет неправильно и в таком случае лучше оставить поле пустым', verbose_name='SEO keys'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_title',
            field=models.TextField(blank=True, help_text='Обязательно для заполнения', verbose_name='SEO title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='service_type',
            field=models.CharField(blank=True, choices=[('установка', 'Установка'), ('разработка', 'Разработка')], help_text='Выбрать из списка тип услуги, если тип товара установлен как услуга, иначе оставить пустым', max_length=20, verbose_name='Тип услуги'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(help_text='Созданый слаг редактировать не рекомендуется', max_length=300, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, help_text='Для видео необходим скриншот будет лучше, если загружать оптимизированное видео', upload_to='video/%Y/%m/%d', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='product',
            name='video_shot',
            field=models.ImageField(blank=True, help_text='Скриншот для видео, размер скриншота должен соответствовать размеру изображения         товара или соотношение сторон должно быть одинаковым', upload_to='video/shot/%Y/%m/%d', verbose_name='Заставка для видео'),
        ),
        migrations.AlterField(
            model_name='product',
            name='year',
            field=models.CharField(blank=True, db_index=True, help_text='Текст', max_length=100, verbose_name='Год выпуска'),
        ),
    ]
