# Generated by Django 4.0.4 on 2022-06-28 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0065_alter_product_attribute_alter_product_available_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('id',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ('id',), 'verbose_name_plural': 'галерея'},
        ),
    ]
