# Generated by Django 4.0.4 on 2022-06-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0066_alter_category_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_preview',
            field=models.ImageField(blank=True, null=True, upload_to='blog_posts/%Y/%m/%d', verbose_name='изображение'),
        ),
    ]
