# Generated by Django 4.0.4 on 2022-07-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0067_alter_post_image_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='box',
            field=models.CharField(blank=True, choices=[('CARTON_BOX_XS', 'Коробка XS (0,5 кг 17х12х9 см)'), ('CARTON_BOX_S', 'Коробка S (2 кг 21х20х11 см)'), ('CARTON_BOX_M', 'Коробка M (5 кг 33х25х15 см)'), ('CARTON_BOX_L', 'Коробка L (12 кг 34х33х26 см)'), ('CARTON_BOX_500GR', 'Коробка (0,5 кг 17х12х10 см)'), ('CARTON_BOX_1KG', 'Коробка (1 кг 24х17х10 см)'), ('CARTON_BOX_2KG', 'Коробка (2 кг 34х24х10 см)'), ('CARTON_BOX_3KG', 'Коробка (3 кг 24х24х21 см)'), ('CARTON_BOX_5KG', 'Коробка (5 кг 40х24х21 см)'), ('CARTON_BOX_10KG', 'Коробка (10 кг 40х35х28 см)'), ('CARTON_BOX_15KG', 'Коробка (15 кг 60х35х29 см)'), ('CARTON_BOX_20KG', 'Коробка (20 кг 47х40х43 см)'), ('CARTON_BOX_30KG', 'Коробка (30 кг 69х39х42 см)'), ('BUBBLE_WRAP', 'Воздушно-пузырчатая пленка'), ('WASTE_PAPER', 'Макулатурная бумага'), ('CARTON_FILLER', 'Прессованный картон "филлер" (55х14х2,3 см)')], default='WASTE_PAPER', max_length=20, verbose_name='Тип упаковки СДЕК'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.IntegerField(blank=True, default=1500, verbose_name='Вес товара СДЕК'),
        ),
    ]
