# Generated by Django 4.0.4 on 2022-07-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0068_product_box_product_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='box',
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.IntegerField(blank=True, default=1500, help_text='Вес товара должен быть указан в граммах', verbose_name='Вес товара СДЕК'),
        ),
    ]
