# Generated by Django 4.0.4 on 2022-07-08 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0069_remove_product_box_alter_product_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Категорию', 'verbose_name_plural': '5.Категории'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('status',), 'verbose_name_plural': '4.Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'verbose_name': 'Заказ', 'verbose_name_plural': '1.Заказы'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('publish',), 'verbose_name_plural': '3.Обзоры'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('id',), 'verbose_name': 'Товар', 'verbose_name_plural': '2.Товары'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ('id',), 'verbose_name_plural': '6.Галерея'},
        ),
    ]
