# Generated by Django 4.0.4 on 2022-07-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0070_alter_category_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='frame_video',
            field=models.TextField(blank=True, default=''),
        ),
    ]
