# Generated by Django 4.0.4 on 2022-07-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0071_product_frame_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retail_crm_site', models.CharField(max_length=100, unique=True)),
                ('retail_crm_host', models.CharField(max_length=100, unique=True)),
                ('retail_crm_uuid', models.CharField(max_length=100, unique=True)),
                ('yookassa_account_id', models.CharField(max_length=100, unique=True)),
                ('yookassa_secret_key', models.CharField(max_length=100, unique=True)),
                ('yookassa_wite_time', models.IntegerField(default=600)),
                ('cdek_client_id', models.CharField(max_length=100, unique=True)),
                ('cdek_client_secret', models.CharField(max_length=100, unique=True)),
                ('cdek_percent', models.IntegerField(default=5)),
            ],
        ),
    ]
