# Generated by Django 4.0.4 on 2022-07-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0072_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='yookassa_redirect_page',
            field=models.CharField(default='https://', max_length=100, unique=True),
        ),
    ]
