# Generated by Django 4.0.4 on 2022-07-23 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0073_config_yookassa_redirect_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'verbose_name_plural': '7.Настройки'},
        ),
        migrations.RemoveField(
            model_name='config',
            name='cdek_percent',
        ),
    ]
