# Generated by Django 4.0.4 on 2022-07-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0075_delete_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='retail_crm_status',
            field=models.CharField(blank=True, max_length=30, verbose_name='RetailCRM статус'),
        ),
    ]
