# Generated by Django 4.0.4 on 2022-07-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0076_order_retail_crm_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='retail_crm_status',
            field=models.CharField(blank=True, max_length=30, verbose_name='CRM_ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('arc', 'В архиве')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
